apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-env
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: backend-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: backend-secret
